### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by Azzurite** [bhauman/figwheel-main-template#12]
In `core.cljs`, there is the println `This text is printed from src/{{nested-dirs}}.cljs` and various other uses of `nested-dirs`.

However, on Windows, `nested-dirs` contains a path with backslashes. This results in a compile error

>[Figwheel:SEVERE] clojure.lang.ExceptionInfo: C:\dev\code\clojure\playground\src\playground\core.cljs [line 19, col 39] Unsupported escape character: \c.

as the string trying to be printed is `"This text is printed from src/playground\core.cljs [...]"`

**Comment by adicirstei** [comment]
The same issue arises form the use of `{{nested-dirs}}` as well on line 31 and subsequent ones :

```clojure
[:h3 "Edit this in src/{{nested-dirs}}.cljs and watch it change!"]
```

Regards,

PS. great work, btw.

Thanks,
Adrian
