### ISSUE TITLE
Outdated documentation for clj-new

### ISSUE THREAD

**Issue by manuel-colmenero** [bhauman/figwheel-main-template#26]
Hi there, 
I followed the steps in the readme file and got an error:
```
$ clj -A:new figwheel-main hello-world.core -- +npm-bundle --reagent
WARNING: When invoking clojure.main, use -M
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
figwheel-main (Datei oder Verzeichnis nicht gefunden)
```
That `clj-new` command seems to be outdated, here is what I did to get it to work, following the `clj-new` documentation:
```
$ clj -X:new create :template figwheel-main :name mcg/hello-world
```
A couple of things changed:
- `-X` is used instead of `-A`
-  `create` is now needed, as there are now other commands like `generate`
- Properties are passed as `:key <value>` and
- A qualified name or a dotted name is required (qualified seems to be encouraged).

Also maybe worth mentioning, one needs a pretty recent version of clj.tools for this new `clj-new` to work.

I'd suggest updating the documentation, or linking a `clj-new`-Readme version that matches the old syntax.

Thank you for Figwheel and all the stuff, and have a good one!

**Comment by manuel-colmenero** [comment]
PS: I can also open a PR if you want.

**Comment by bhauman** [comment]
A PR would be great!!
